# Generated by Django 4.1.4 on 2023-01-02 09:53

from django.db import migrations, models
import visitormanagement.validators


class Migration(migrations.Migration):

    dependencies = [
        ('visitormanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='visitor_name',
            field=models.CharField(max_length=180, validators=[visitormanagement.validators.name_validatior]),
        ),
    ]
