# Generated by Django 4.1.7 on 2023-03-01 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitormanagement', '0002_alter_visitors_visitor_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitors',
            options={'ordering': ['-visitor_date'], 'permissions': [('custom_can_add_visitor_form', 'can add visitor form')], 'verbose_name': 'Visitor data'},
        ),
    ]
