# Generated by Django 4.1.7 on 2023-04-02 05:47

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('visitormanagement', '0003_alter_visitors_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='visitor_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='visitor_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
