# Generated by Django 4.1.7 on 2023-04-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitormanagement', '0004_alter_visitors_visitor_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitors',
            name='visitor_organization',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
