# Generated by Django 4.1.7 on 2023-08-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitormanagement', '0005_visitors_visitor_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitors',
            name='checkout_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='visitor check-out time'),
        ),
        migrations.AddField(
            model_name='visitors',
            name='visitor_status',
            field=models.CharField(blank=True, choices=[('ARRIVED', 'Arrived'), ('ONSITE', 'On-Site'), ('WAITING_APPROVAL', 'Waiting Approval'), ('DEPARTED', 'Departed')], default='ARRIVED', help_text='this field denotes whether the visitor is still on the site or left', max_length=20, null=True, verbose_name='visitor status'),
        ),
    ]
