# Generated by Django 4.1.7 on 2023-09-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitormanagement', '0007_alter_visitors_visitor_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='visitor_status',
            field=models.CharField(blank=True, choices=[('ARRIVED', 'Arrived'), ('ONSITE', 'On-Site'), ('WAITING_APPROVAL', 'Waiting Approval'), ('DEPARTED', 'Departed')], default='DEPARTED', help_text='this field denotes whether the visitor is still on the site or left', max_length=20, null=True, verbose_name='visitor status'),
        ),
    ]
