# Generated by Django 4.1.7 on 2023-08-31 05:41

from django.db import migrations, models
import sms_service.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_body', models.TextField(help_text='The body of the sms that was sent', max_length=350, verbose_name='sms body')),
                ('phone_number', models.CharField(help_text='the phone number to which the sms was sent', max_length=15, validators=[sms_service.validators.validate_phone_number], verbose_name='phone number')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='the date-time when the sms was sent', verbose_name='sms timestamp')),
                ('is_delivered', models.BooleanField(blank=True, default=False, help_text='the sms delivery status', null=True, verbose_name='sms delivered')),
                ('api_response', models.JSONField(blank=True, help_text='the response data that was sent from the sms delivery api endpoint', null=True, verbose_name='api response')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
