# For more information, please refer to https://aka.ms/vscode-docker-python
FROM python:3.10

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

WORKDIR /app

COPY requirements.txt /app/requirements.txt
RUN pip3 install -r requirements.txt

COPY deployment/start-app /app/deployment/start-app
RUN sed -i 's/\r$//g' /app/deployment/start-app
RUN chmod +x /app/deployment/start-app

COPY deployment/entrypoint /app/deployment/entrypoint
RUN sed -i 's/\r$//g' /app/deployment/entrypoint
RUN chmod +x /app/deployment/entrypoint

COPY deployment/clear-docker-project /app/deployment/clear-docker-project
RUN sed -i 's/\r$//g' /app/deployment/clear-docker-project
RUN chmod +x /app/deployment/clear-docker-project

COPY deployment/clear-junk /app/deployment/clear-junk
RUN sed -i 's/\r$//g' /app/deployment/clear-junk
RUN chmod +x /app/deployment/clear-junk

ENTRYPOINT ["/app/deployment/entrypoint"]


