# Generated by Django 4.1.4 on 2023-01-02 07:55

from django.db import migrations, models
import employee.validators


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_name',
            field=models.CharField(max_length=200, validators=[employee.validators.name_validaotr]),
        ),
    ]
