# Generated by Django 4.1.4 on 2023-01-02 08:37

from django.db import migrations, models
import employee.validators


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_employee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_name',
            field=models.CharField(max_length=200, validators=[employee.validators.name_validaotr, employee.validators.length_validator, employee.validators.string_validator]),
        ),
    ]
