# Generated by Django 4.1.7 on 2023-08-31 10:13

from django.db import migrations, models
import employee.validators


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_alter_employee_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Employee phone number', max_length=15, null=True, validators=[employee.validators.validate_phone_number], verbose_name='Employee phone number'),
        ),
    ]
