# Generated by Django 4.1.7 on 2023-08-30 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otp_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otp',
            options={'ordering': ['is_verified'], 'verbose_name': 'Otp Code'},
        ),
        migrations.RenameField(
            model_name='otp',
            old_name='is_varified',
            new_name='is_verified',
        ),
    ]
