# Generated by Django 4.1.7 on 2023-08-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_system', '0003_alter_otp_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_code',
            field=models.CharField(help_text='OTP code after hashing', max_length=200, verbose_name='OTP code'),
        ),
    ]
