# Generated by Django 4.1.7 on 2023-03-02 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_token', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitortoken',
            options={'permissions': [('custom_can_download_visitor_token', 'can download visitor token')]},
        ),
    ]
