# Generated by Django 4.1.4 on 2023-01-03 07:04

from django.db import migrations, models
import employee.validators


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_customuser_first_name_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[employee.validators.email_validator], verbose_name='email address'),
        ),
    ]
