# Generated by Django 4.1.7 on 2023-03-03 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': (('can_delete_instance', 'can delete'), ('can_read_instance', 'can read'), ('can_update_instance', 'can update'), ('can_create_instance', 'can create'), ('custom_can_see_permissions', 'can  add department'))},
        ),
    ]
