# Generated by Django 4.1.7 on 2023-03-03 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': (('can_delete_instance', 'can delete'), ('can_read_instance', 'can read'), ('can_update_instance', 'can update'), ('can_create_instance', 'can create'), ('custom_can_view_permissions', 'can  view permissions'))},
        ),
    ]
