# Generated by Django 4.1.7 on 2023-03-02 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitingpurpose', '0005_alter_visitingpurpose_purpose_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitingpurpose',
            options={'ordering': ['-purpose_name'], 'permissions': [('custom_can_add_visiting_reason', 'can  add visiting reason'), ('custom_can_update_visiting_reason', 'can  update visiting reason'), ('custom_can_delete_visiting_reason', 'can  delete visiting reason')], 'verbose_name': 'purpose name'},
        ),
    ]
