from .analytics_view import AnalyticsView, Visitor_details_by_date_search, Visitor_details_by_date_search_report, visitor_details_all_report, VisitorDetailsExcelExport

from .analyticsApi import ResonWiseVisitorChart, NumberofVisitorsPerMonth, DepartmentWiseVisitorChart
