# Generated by Django 4.1.4 on 2023-01-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=200, unique=True)),
                ('department_description', models.TextField(max_length=400)),
            ],
            options={
                'verbose_name': 'Department details',
                'ordering': ['-department_name'],
                'permissions': [('update_department_name_and_details', 'Can update the department name and details ')],
            },
        ),
    ]
