# Generated by Django 4.1.4 on 2023-01-02 09:18

import department.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(max_length=200, unique=True, validators=[department.validators.name_validator]),
        ),
    ]
