# Generated by Django 4.1.7 on 2023-03-02 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_alter_department_department_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['-department_name'], 'permissions': [('custom_can_add_department', 'can  add department'), ('custom_can_update_department', 'can  update department'), ('custom_can_delete_department', 'can  delete department')], 'verbose_name': 'Department details'},
        ),
    ]
